name: prettier
run-name: ${{ github.actor }} - prettier code

on:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.8"
      - run: npm install
      - run: npm run prettier
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
